# GitLab Runner Configuration for Resource Management
# Đây là file cấu hình cho GitLab Runner để giới hạn tài nguyên CI/CD

concurrent = 2  # Số job CI/CD chạy đồng thời tối đa
check_interval = 0
log_level = "info"

[session_server]
  session_timeout = 1800

# Template runner - cần được register với GitLab
# Chạy script: ./scripts/register-runner.sh để tự động register

# Docker Executor Runner (Khuyến nghị cho hầu hết use cases)
[[runners]]
  name = "docker-runner"
  url = "http://gitlab:80/"  # Internal network URL
  token = ""  # Sẽ được điền tự động khi register
  executor = "docker"
  
  # Runner-specific settings
  limit = 1  # Max jobs cho runner này
  
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    
    # Volumes - cho phép access Docker socket và cache
    volumes = [
      "/cache",
      "/var/run/docker.sock:/var/run/docker.sock"
    ]
    
    # Resource limits per job
    memory = "1g"           # Giới hạn RAM cho mỗi job
    memory_swap = "2g"      # Giới hạn swap
    memory_reservation = "512m"  # Reserved memory
    
    # CPU limits per job  
    cpus = "1.0"           # Giới hạn CPU cores cho mỗi job
    cpu_shares = 1024      # CPU shares (relative weight)
    
    # Storage settings
    shm_size = 268435456   # 256MB shared memory
    
    # Network settings
    network_mode = "gitlab_net"
    
    # Security settings
    security_opt = ["no-new-privileges:true"]
    cap_drop = ["ALL"]
    cap_add = ["CHOWN", "DAC_OVERRIDE", "FOWNER", "SETGID", "SETUID", "NET_BIND_SERVICE"]
    
    # Environment variables for all jobs
    environment = [
      "DOCKER_DRIVER=overlay2",
      "DOCKER_TLS_CERTDIR="
    ]

# Shell Executor Runner (cho local builds)
[[runners]]
  name = "shell-runner"
  url = "http://gitlab:80/"
  token = ""  # Sẽ được điền tự động khi register
  executor = "shell"
  
  limit = 1
  
  [runners.shell]
    # Shell executor chạy trực tiếp trên host
    # Cần cài đặt dependencies trực tiếp trên host

# Cache configuration
[runners.cache]
  Type = "local"
  Path = "/cache"
  
  [runners.cache.local]
    MaxCacheSize = "1G"  # Giới hạn cache size
